name: Build Cross-Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 添加手动触发

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            target: node18-win-x64
            output: puppeteer-automation-win.exe
          - os: macos-latest
            target: node18-macos-x64
            output: puppeteer-automation-macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4  # 更新到最新版本
    
    - name: Setup Node.js
      uses: actions/setup-node@v4  # 更新到最新版本
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci  # 使用ci而不是install
    
    - name: Install Chrome
      run: npm run install-chrome
    
    - name: Build executable
      run: npx pkg package.json --targets ${{ matrix.target }} --output ${{ matrix.output }}
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4  # 更新到最新版本
      with:
        name: ${{ matrix.output }}
        path: ${{ matrix.output }}
        retention-days: 30  # 设置保留天数
